# Generated by Django 4.1.7 on 2023-03-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Поле будет изменено при обновлении любого из полей модели.', null=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=1024, unique=True, verbose_name='Название объекта')),
                ('parents', models.ManyToManyField(related_name='children', to='entities.typegrade', verbose_name='Родительский объект')),
            ],
            options={
                'verbose_name': 'Грейд типа объекта',
                'verbose_name_plural': 'Грейды типов объектов',
            },
        ),
    ]
