# Generated by Django 4.1.7 on 2023-03-13 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0002_entitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Поле будет изменено при обновлении любого из полей модели.', null=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=1024, unique=True, verbose_name='Наименование объекта')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаленного объекта')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='entities.entity', verbose_name='Родительский объект')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='entities.entitytype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
