# Generated by Django 4.1.7 on 2023-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_entity_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typegrade',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='entities.typegrade', verbose_name='Родительский объект'),
        ),
    ]
