# Generated by Django 4.1.7 on 2023-03-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_entity_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytype',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_types', to='entities.typegrade', verbose_name='Грейд типа объекта'),
        ),
    ]
