# Generated by Django 4.1.7 on 2023-03-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_entitytype_grade'),
        ('entities', '0005_alter_typegrade_parents'),
    ]

    operations = [
    ]
