# Generated by Django 4.1.7 on 2023-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_merge_20230313_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Наименование объекта'),
        ),
    ]
