# Generated by Django 4.1.7 on 2023-04-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_merge_20230313_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytype',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_types', to='entities.typegrade', verbose_name='Грейд типа объекта'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='title',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Название типа объекта'),
        ),
    ]
