# Generated by Django 4.1.7 on 2023-04-11 11:23

from django.db import migrations


VARCHAR_VALUE_TYPE_TITLE = 'VARCHAR'
EQUIPMENT_ENTITY_TITLE = 'Оборудование'
AREA_ENTITY_TITLE = 'Площадка'


def create_entity_type(apps, attributes_data, entity_type_title):
    Attribute = apps.get_model('attributes', 'Attribute')
    EntityType = apps.get_model('entities', 'EntityType')

    attribute_ids = [
        Attribute.objects.update_or_create(
            title=attr.get('title'),
            defaults={'value_type': attr.get('value_type')},
        )[0].pk
        for attr in attributes_data
    ]

    entity_type, _ = EntityType.objects.get_or_create(title=entity_type_title)
    entity_type.attributes.set(attribute_ids, clear=True)


def add_default_entity_types(apps, schema_editor):
    ValueType = apps.get_model('catalogs', 'ValueType')

    varchar_value_type, _ = ValueType.objects.get_or_create(title=VARCHAR_VALUE_TYPE_TITLE)

    equipment_attributes_data = [
        {
            'title': 'Модель',
            'value_type': varchar_value_type,
        },
        {
            'title': 'Артикул производителя',
            'value_type': varchar_value_type,
        },
        {
            'title': 'Производитель',
            'value_type': varchar_value_type,
        },
    ]
    area_attributes_data = [
        {
            'title': 'Адрес',
            'value_type': varchar_value_type,
        },
        {
            'title': 'Описание',
            'value_type': varchar_value_type,
        },
    ]

    create_entity_type(apps, equipment_attributes_data, EQUIPMENT_ENTITY_TITLE)
    create_entity_type(apps, area_attributes_data, AREA_ENTITY_TITLE)


def backward(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_entitytype_grade_alter_entitytype_title'),
        ('attributes', '0005_alter_attribute_measurement'),
        ('catalogs', '0002_add_values'),
    ]

    operations = [
        migrations.RunPython(add_default_entity_types, reverse_code=backward),
    ]
