# Generated by Django 4.1.7 on 2023-04-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_entity_title'),
        ('entities', '0008_add_default_entity_types_with_attributes'),
    ]

    operations = [
    ]
