# Generated by Django 4.1.7 on 2023-03-13 12:19

from django.db import migrations


value_types_initial_data = [
    {
        'title': 'INT',
    },
    {
        'title': 'VARCHAR',
    },
    {
        'title': 'DATETIME',
    }
]


def forward(apps, schema_editor):
    ValueType = apps.get_model('catalogs', 'ValueType')
    ValueType.objects.bulk_create(
        [ValueType(**data) for data in value_types_initial_data],
        ignore_conflicts=True,
    )


def backward(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=backward),
    ]
