# Generated by Django 4.1.7 on 2023-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Поле будет изменено при обновлении любого из полей модели.', null=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название единицы измерения')),
                ('description', models.TextField(verbose_name='Описание единицы измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
    ]
