# Generated by Django 4.1.7 on 2023-03-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_add_values'),
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Поле будет изменено при обновлении любого из полей модели.', null=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название атрибута')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attributes.measurementunit', verbose_name='Единица измерения атрибута')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.valuetype', verbose_name='Тип значения атрибута')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
    ]
