# Generated by Django 4.1.7 on 2023-03-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_entity'),
        ('attributes', '0002_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Поле будет изменено при обновлении любого из полей модели.', null=True, verbose_name='Дата последнего обновления')),
                ('value', models.CharField(max_length=1024, verbose_name='Значения атрибута')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='attributes.attribute', verbose_name='Атрибут')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='entities.entity', verbose_name='Объект')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
