# Generated by Django 4.1.7 on 2023-03-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_add_values'),
        ('attributes', '0003_attributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='attributes.measurementunit', verbose_name='Единица измерения атрибута'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='catalogs.valuetype', verbose_name='Тип значения атрибута'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.TextField(verbose_name='Значения атрибута'),
        ),
    ]
