# Generated by Django 4.1.7 on 2023-04-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_alter_attribute_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='attributes.measurementunit', verbose_name='Единица измерения атрибута'),
        ),
    ]
